### ISSUE TITLE
training MAPPO and RMAPPO with MPE gives an error!

### ISSUE THREAD

**Issue by kailashg26** [marlbenchmark/on-policy#55]
Hello,
Thanks for the code base and indeed a really good work!
I was trying to replicate the results from the paper and started with MPE environment with mappo and rmappo.
But I when I train the rmappo with MPE, I get the following error:
```
env is MPE, scenario is simple_spread, algo is mappo, exp is check, max seed is 1
seed is 1:
choose to use gpu...
Traceback (most recent call last):
  File "train/train_mpe.py", line 167, in <module>
    main(sys.argv[1:])
  File "train/train_mpe.py", line 152, in main
    runner.run()
  File "/home/kailash/Desktop/on-policy/onpolicy/runner/shared/mpe_runner.py", line 47, in run
    self.save()
  File "/home/kailash/Desktop/on-policy/onpolicy/runner/shared/base_runner.py", line 134, in save
    policy_vnorm = self.trainer.policy.value_normalizer
AttributeError: 'R_MAPPOPolicy' object has no attribute 'value_normalizer'
```
when I train the mappo with MPE, I get the following error:
```
env is MPE, scenario is simple_spread, algo is mappo, exp is check, max seed is 1
seed is 1:
Traceback (most recent call last):
  File "train/train_mpe.py", line 167, in <module>
    main(sys.argv[1:])
  File "train/train_mpe.py", line 71, in main
    assert (all_args.use_recurrent_policy == False and all_args.use_naive_recurrent_policy == False), ("check recurrent policy!")
AssertionError: check recurrent policy!
```

Please let me know if there is any mistake I did. Thanks for the help!

**Comment by HosnLS** [comment]
Thanks for reporting the bug!
For the first one, it was caused by a recent commit on "shared runner". A new PR has been raised to fix it.
For the second one, you may have used some arguments incorrectly. Please note that "rmappo" requires either "use_recurrent_policy" or "use_naive_recurrent_policy" enabled, but "mappo" requires neither. When useing "mappo
, you may add "--use_recurrent_policy" in the trainging script to disable recurrent policy, which is enabled by default.

**Comment by kailashg26** [comment]
Thank you! Now it works.
