### ISSUE TITLE
An error occurs when I run rmappo on football

### ISSUE THREAD

**Issue by cugbbaiyun** [marlbenchmark/on-policy#58]
The output of python is listed here:

Traceback (most recent call last):
  File "train/train_football.py", line 203, in <module>
    main(sys.argv[1:])
  File "train/train_football.py", line 188, in main
    runner.run()
  File "/onpolicy/runner/shared/football_runner.py", line 43, in run
    self.insert(data)
  File /onpolicy/runner/shared/football_runner.py", line 141, in insert
    masks=masks
TypeError: insert() got an unexpected keyword argument 'rnn_states'

**Comment by cugbbaiyun** [comment]
The total output of python is listed here:

Traceback (most recent call last):
  File "train/train_football.py", line 203, in <module>
    main(sys.argv[1:])
  File "train/train_football.py", line 188, in main
    runner.run()
  File "/home/byp/several_trys/svmappo/onpolicy/runner/shared/football_runner.py", line 43, in run
    self.insert(data)
  File "/home/byp/several_trys/svmappo/onpolicy/runner/shared/football_runner.py", line 141, in insert
    masks=masks
TypeError: insert() got an unexpected keyword argument 'rnn_states'

I think this should be solved as this:

```
rnn_states_actor=rnn_states,
```

in football_runner.py, line 135.

**Comment by zoeyuchao** [comment]
yes, thx, already fix this.

**Comment by LINGYUNFDU** [comment]
> 

Hi, where can I the find the fixed version?
