### ISSUE TITLE
GPU error

### ISSUE THREAD

**Issue by ingo-ch** [marlbenchmark/on-policy#6]
Hi

The code works in cpu but I get the below problem with gpu:

```
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Full details are below:

```
env is Hanabi, algo is mappo, exp is mlp_critic1e-3_entropy0.015_v0belief, max seed is 1
seed is 1:
choose to use gpu...
Traceback (most recent call last):
  File "train/train_hanabi_forward.py", line 176, in <module>
    main(sys.argv[1:])
  File "train/train_hanabi_forward.py", line 161, in main
    runner.run()
  File "/nfs/home/ic/on-policy/onpolicy/runner/shared/hanabi_runner_forward.py", line 50, in run
    self.collect(step) 
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/home/ic/on-policy/onpolicy/runner/shared/hanabi_runner_forward.py", line 153, in collect
    self.use_available_actions[choose])
  File "/nfs/home/ic/on-policy/onpolicy/algorithms/r_mappo/algorithm/rMAPPOPolicy.py", line 71, in get_actions
    deterministic)
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/home/ic/on-policy/onpolicy/algorithms/r_mappo/algorithm/r_actor_critic.py", line 62, in forward
    actor_features = self.base(obs)
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/home/ic/on-policy/onpolicy/algorithms/utils/mlp.py", line 54, in forward
    x = self.mlp(x)
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/home/ic/on-policy/onpolicy/algorithms/utils/mlp.py", line 25, in forward
    x = self.fc1(x)
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/nfs/home/ic/miniconda3/envs/marl/lib/python3.7/site-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
training is done!
```

I get the error with both cuda 10.1 and 11.2. Do you have any thoughts on how to fix this? Many thanks!

**Comment by testMondey** [comment]
how did you fix it？
